config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get"/home/about" => "homes#about" ,as: "about"
  devise_for :users
  resources :users, only: [:edit, :update,:index, :show] do
    resources :reading_logs, only: [:index]
    resource :relationships, only: [:create, :destroy]
     get "followers" => "relationships#followers", as: "followers"
  	 get "followeds" => "relationships#followeds", as: "followeds"
     get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy, :index]
    resource :reading_status, only: [:create, :update, :destroy] 
    resource :bookmark, only: [:create, :destroy]   
  end  
  get "search" => "searches#search"
  resources :rooms, only: [:create, :show] do      
    resources :messages, only: [:create]
  end
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :destroy] 
  end
  get "tag_searches/search" => "tag_searches#search"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :notifications, only: [:update]
  resources :reading_logs        
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_one_attached :group_image
  has_many :users, through: :group_users, source: :user
  has_many :group_messages, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end

  def is_owned_by?(user)
    owner.id == user.id
  end 

  def include_user?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
    @user = User.find(current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path, notice: 'グループを削除しました。'
  end

  private

    def group_params
      params.require(:group).permit(:name, :introduction, :group_image)
    end

    def ensure_correct_user
      @group = Group.find(params[:id])
      unless @group.owner_id == current_user.id
        redirect_to groups_path
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true do |f| %>

  <div class="form-group">
    <%= f.label :name, "Group name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :introduction, "Group introduction" %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :group_image, "Group image" %>
    <%= f.file_field :group_image, class: "form-control-file", accept: "image/*" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>

<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Group image</th>
      <th>Group name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= link_to "Show", group, class: "group_#{group.id}" %></td>
      <% if group.is_owned_by?(current_user) %>
        <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-success group_#{group.id}" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <%= render 'layouts/error_messages', resource: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-3">   
      <%= render 'books/book', { book: @book, user: @user, from: 'groups_index' } %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>New Group</h3>
      <%= render 'layouts/error_messages', resource: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row mt-4'>
    <div class='col-md-3'>
      <%= render 'books/book', { book: @book, user: @user, from: 'groups_index' } %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>Group image</th>
            <th>Group name</th>
            <th>Group introduction</th>
            <th colspan="1"></th>
            <th>Group member</th>
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td><%= image_tag @group.get_group_image, size: '50x50' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
              <% else %>
                <% if @group.include_user?(current_user) %>
                  <%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-success" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% @group.users.each do |user| %>
                <li style="list-style:none;"><%= user.name %></li>
              <% end %>
            </td>            
          </tr>
        </tbody>  
      </table>

      <h3>Notification</h3>
      <%= link_to "New notification", new_group_group_message_path(@group), class: "btn btn-primary mb-2" %>
      <% if @group.group_messages.any? %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Title</th>
              <th>Opinion</th>
              <th>Poster</th>
              <th>Datetime</th>
              <% if @group.owner_id == current_user.id %>
                <th></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% @group.group_messages.order(created_at: :desc).each do |group_message| %>
              <tr>
                <td><%= group_message.title %></td>
                <td><%= group_message.body %></td>
                <td><%= group_message.user.name %></td>
                <td><%= group_message.created_at.strftime('%Y/%m/%d %H:%M') %></td>
                <% if @group.owner_id == current_user.id %>
                  <td><%= link_to "Destroy", group_group_message_path(@group, group_message), method: :delete, data: { confirm: "本当によろしいですか？" }, class: "btn btn-danger btn-sm" %></td>  
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>このグループからのお知らせはまだありません。</p>
      <% end %>

    </div>
  </div>
</div> 