config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get"/home/about" => "homes#about" ,as: "about"
  devise_for :users
  resources :users, only: [:edit, :update,:index, :show] do
    resources :reading_logs, only: [:index]
    resource :relationships, only: [:create, :destroy]
     get "followers" => "relationships#followers", as: "followers"
  	 get "followeds" => "relationships#followeds", as: "followeds"
     get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy, :index]
    resource :reading_status, only: [:create, :update, :destroy] 
    resource :bookmark, only: [:create, :destroy]   
  end  
  get "search" => "searches#search"
  resources :rooms, only: [:create, :show] do      
    resources :messages, only: [:create]
  end
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :destroy] 
  end
  get "tag_searches/search" => "tag_searches#search"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :notifications, only: [:update]
  resources :reading_logs        
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :reading_statuses 
  has_many :reading_books, through: :reading_statuses, source: :book
  has_one_attached :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :view_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :owned_groups, class_name: "Group", foreign_key: "owner_id", dependent: :destroy
  has_many :group_messages, dependent: :destroy 
  has_many :notifications, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_books, through: :bookmarks, source: :book
  has_many :posted_books, class_name: 'Book', foreign_key: 'user_id', dependent: :destroy
  has_many :reading_logs, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true , presence: true
  validates :introduction, length: { maximum: 50 }

  # プロフィール画像取得、リサイズする
  def get_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # Userモデルのnameカラムに対して検索
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followeds, through: :active_relationships, source: :followed
  # フォローされているユーザーを取得
  has_many :followers, through: :passive_relationships, source: :follower

   # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  
  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followeds.include?(user)
  end

  # ゲストログインのパスワード、名前の設定
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]

  # ユーザー編集画面
  def edit
    @user = User.find(params[:id])
  end

  # ユーザー編集処理
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Book was successfully editing."
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "Book was make a mistake editing."
      render :edit
    end 
  end

  # ユーザー一覧画面
  def index
    @users = User.page(params[:page])
    @user = current_user
    @book = Book.new
    @currentUserEntry = Entry.where(user_id: current_user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu| 
        @userEntry.each do |u| 
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end 
  end

  # ユーザー詳細画面
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.posted_books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @bookmarked_books = @user.bookmarked_books
  end

  def daily_posts  
    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  private

  # 許可したカラムだけ保存、更新する
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  # ログイン中のユーザーだけが、自分のページを操作できるようにするためのメソッド
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "Search" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<div class="container">
  <div class="row mt-4">

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2> 
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Follower</th>
            <th>Followed</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td style="width: 100px;"><%= image_tag user.get_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= user.followeds.count %></td>
            <td><%= user.followers.count %></td>
            <td><%= render "relationships/btn", user: user %></td>            
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @users %>
      </div>      
    </div>
  </div>
</div>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h3>検索結果</h3>
  <div class="card mb-3" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any? %>
  <%= @user.errors.count %>errors have occurred
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> 
    <label for="inputName">Introduction</label>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-md-3">
       <%= render 'books/book', {book: @book, user: @user, from: "user"} %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2> 
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Follow</th>
            <th>Follower</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td style="width: 100px;"><%= image_tag user.get_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= user.followeds.count %></td>
            <td><%= user.followers.count %></td>
            <td>
              <%= render "relationships/btn", user: user %>

              <% if user != current_user && current_user.following?(user) && user.following?(current_user) %>
                <% shared_room = current_user.entries.joins(:room).merge(Room.joins(:entries).where(entries: { user_id: user.id })).first %>
                
                <% if shared_room.present? %>
                  <%= link_to "メッセージへ", room_path(shared_room.room), class: "btn btn-primary mt-3" %>
                <% else %>
                  <%= form_with url: rooms_path, method: :post do |f| %>
                    <%= hidden_field_tag "entry[user_id]", user.id %>
                    <%= f.submit "メッセージを始める", class: "btn btn-primary mt-3" %>
                  <% end %>
                <% end %>
              <% end %>             
            </td> 
            <td><%= link_to "Show", user_path(user.id) %></td>
            <td><%= link_to "グループを作成する", new_group_path %> |
                <%= link_to "グループ一覧", groups_path %>
            </td>    
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center">
        <%= paginate @users %>
      </div>      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class= "container">
  <div class= "row mt-4">
    <div class= "col-md-3">
      <%= render 'books/book', {book: @book, user: @user, from: "user"} %>
    </div>

    <div class="col-md-8 offset-md-1"> 
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Comment count</th>
            <th>Favorite count</th>
          </tr>
        </thead>
        <tbody>
          <% @user.posted_books.each do |book| %>
          <tr>
            <td style="width: 100px;"><%= link_to user_path(@user.id) do %>
              <%= image_tag @user.get_image(100,100)%>
            <% end %></td>
            <td style="word-break: break-word;"><%= link_to book.title, book_path(book.id) %></td> 
            <td style="word-break: break-word;"><%= book.body %></td>
            <td><%= book.book_comments.count %></td>
            <td><%= render 'favorites/btn', book: book %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <h3>読書記録</h3>
      <div class="mb-3">
        <%= link_to "📅 読書記録カレンダーを見る", reading_logs_path, class: "btn btn-outline-primary mr-2" %>
        <%= link_to "📝 新しい読書記録を追加", new_reading_log_path, class: "btn btn-outline-success" %>
      </div>

      <% if current_user.reading_logs.any? %>
        <h4>これまでの記録一覧</h4>
        <ul class="list-group mb-3">
          <% current_user.reading_logs.each do |log| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <div>
                <strong><%= log.read_on.strftime('%Y/%m/%d') %></strong> - <%= log.book.title %>
              </div>
              <div>
                <%= link_to "編集", edit_reading_log_path(log), class: "btn btn-sm btn-secondary" %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>まだ読書記録がありません。</p>
      <% end %>
      


      <h3>Bookmark list</h3>
      <% if @bookmarked_books.any? %>
        <ul>
          <% @bookmarked_books.each do |book| %>
            <li><%= link_to book.title, book_path(book) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>No bookmark list</p>
      <% end %>

      <h3><%= @user.name %>が作成したグループ</h3>
      <% if @user.owned_groups.any? %>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>Group image</th>
              <th>Group name</th>
              <th>Group introduction</th>
              <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.owned_groups.each do |group| %>
              <tr>
                <td><%= image_tag group.get_group_image, size: '50x50' %></td>
                <td><%= link_to group.name, group_path(group) %></td>
                <td><%= group.introduction %></td>
                <td><%= link_to "Show", group_path(group), class: "btn btn-info mb-3" %>
                    <% if group.owner_id == current_user.id %>
                      <%= link_to "New notification", new_group_group_message_path(group), class: "btn btn-primary ml-2" %>
                    <% end %> 
                </td>
                
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p><%= @user.name %>が作成したグループはありません。</p>
      <% end %>
      
      <h3>投稿数の前日比・前週比</h3>
        <div class="table_width">
          <table class='table table-bordered'>
            <thead>
              <tr> 
                <th>今日の投稿数</th>
                <th>前日の投稿数</th>
                <th>前日比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%=  @today_book.count %></td>
                <td><%= @yesterday_book.count %></td>
                <td>
                  <% if @yesterday_book.count == 0 %>
                    前日の投稿が0のため計算できません
                  <% else %>
                    <% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
                    <%= (@the_day_before * 100).round %>%
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="table_width">
          <table class='table table-bordered'>
            <thead>
              <tr> 
                <th>今週の投稿数</th>
                <th>前週の投稿数</th>
                <th>前週比</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @this_week_book.count %></td>
                <td><%= @last_week_book.count %></td>
                <td>
                  <% if @last_week_book.count == 0 %>
                    前週の投稿が0のため計算できません
                  <% else %>
                    <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f  %>
                    <%= (@the_week_before * 100).round %>%
                  <% end %>
                </td>
              </tr>
            </tbody>
          </table>

          <h3>7日間分の投稿数</h3>
            <table class='table table-bordered'>
              <thead>
                <tr> 
                  <th>６日前</th>
                  <th>５日前</th>
                  <th>４日前</th>
                  <th>３日前</th>
                  <th>２日前</th>
                  <th>１日前</th>
                  <th>今日</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @books.created_6day_ago.count %></td>
                  <td><%= @books.created_5day_ago.count %></td>
                  <td><%= @books.created_4day_ago.count %></td>
                  <td><%= @books.created_3day_ago.count %></td>
                  <td><%= @books.created_2day_ago.count %></td>
                  <td><%= @books.created_yesterday.count %></td>
                  <td><%= @books.created_today.count %></td>
                </tr>
              </tbody>
            </table>
            <canvas id="myLineChart"></canvas>
            <script>
              $(document).on('turbolinks:load', function() {
                var ctx = document.getElementById("myLineChart");
                var myLineChart = new Chart(ctx, {
                  type: 'line',
                  data: {
                    labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                    datasets: [
                      {
                        label: '投稿した本の数',
                        data: [
                          <%= @books.created_6day_ago.count %>,
                          <%= @books.created_5day_ago.count %>, 
                          <%= @books.created_4day_ago.count %>, 
                          <%= @books.created_3day_ago.count %>, 
                          <%= @books.created_2day_ago.count %>, 
                          <%= @books.created_yesterday.count %>, 
                          <%= @books.created_today.count %>
                        ],
                        borderColor: "rgba(0,0,255,1)",
                        backgroundColor: "rgba(0,0,0,0)",
                        tension: 0.4
                      }
                    ],
                  },
                  options: {
                    title: {
                      display: true,
                      text: '7日間の投稿数の比較'
                    },
                    responsive: true,
                    scales: {
                      y:{
                        suggestedMin: 0,
                        suggestedMax: 10
                      },
                      x:{
                        stacked: true
                      },
                    },
                  }
                });
              });
            </script>

            <h3>指定した日の投稿数</h3>
            <div class="col-md-8 offset-md-1">
              <%= render 'daily_posts_form', user: @user %>
            </div>

        </div>
    </div>
  </div>
</div>