config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get"/home/about" => "homes#about" ,as: "about"
  devise_for :users
  resources :users, only: [:edit, :update,:index, :show] do
    resources :reading_logs, only: [:index]
    resource :relationships, only: [:create, :destroy]
     get "followers" => "relationships#followers", as: "followers"
  	 get "followeds" => "relationships#followeds", as: "followeds"
     get "daily_posts" => "users#daily_posts"
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy, :index]
    resource :reading_status, only: [:create, :update, :destroy] 
    resource :bookmark, only: [:create, :destroy]   
  end  
  get "search" => "searches#search"
  resources :rooms, only: [:create, :show] do      
    resources :messages, only: [:create]
  end
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    resources :group_messages, only: [:new, :create, :destroy] 
  end
  get "tag_searches/search" => "tag_searches#search"
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :notifications, only: [:update]
  resources :reading_logs        
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :reject_non_related, only: [:show]

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room)
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def reject_non_related
      room = Room.find(params[:id])
      user = room.entries.where.not(user_id: current_user.id).first.user
      unless (current_user.following?(user)) && (user.following?(current_user))
        redirect_to books_path
      end
    end  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<div class="container">
  <!-- ユーザーとのルーム -->
  <% @entries.each do |e| %>
    <% unless e.user == current_user %>
      <div class="row mt-4">
        <div class="col-lg-12">
          <h4><strong><%= e.user.name %>さんとのルーム</strong></h4>
        </div>
      </div>
    <% end %>
  <% end %>

  <!-- 戻るボタン -->
  <div class="row">
    <div class="col-lg-12">
      <div class="left-button">
        <%= link_to "ユーザー一覧に戻る", users_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <hr>

  <!-- ルームセクション -->
  <div class="chat">
    <div class="chats">
      <% if @messages.present? %>
        <div class="row">
          <div class="col-lg-6">
            <div style="text-align: left">
              <% @entries.each do |e| %>
                <% unless e.user == current_user %>
                  <h4><strong><%= e.user.name %>さん</strong></h4>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-lg-6">  
            <div style="text-align: right;">
              <h4><strong><%= current_user.name %>さん</strong></h4>
            </div>  
          </div>  
        </div>
                      
        <% @messages.each do |m| %>
          <div class="row">
            <div class="col-lg-12">
              <% if m.user_id == current_user.id %>
                <!-- 自分のメッセージ -->           
                <div class="chat-fukidashi" style="text-align: right;">
                  <strong><%= m.content %></strong>
                </div>
              <% else %>
                <!-- 他ユーザーのメッセージ -->
                <div class="chat-fukidashi" style="text-align: left;">
                  <strong><%= m.content %></strong>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- エラーメッセージ表示 -->
    <div class="row">
      <div class="col-lg-12">
        <div class="errors">
        </div>
      </div>
    </div>

    <!-- メッセージ投稿フォーム -->
    <div class="row">
      <div class="col-lg-12">
        <div class="posts">
          <%= form_with model: @message, url: room_messages_path(@room), local: false do |f| %>
            <%= f.text_field :content, class: "form-control", placeholder: "140字以内でメッセージを入力してください" %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.submit "新規メッセージ", class: "btn btn-success mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>